package com.tys.legalbases.application.mappers;

import com.tys.legalbases.application.dtos.LegalBaseDTO;
import com.tys.legalbases.application.dtos.LegalBaseRagDTO;
import com.tys.legalbases.application.dtos.LegalBaseSaveDto;
import com.tys.legalbases.application.dtos.NationalNormArticleDTO;
import com.tys.legalbases.domain.model.entity.ArticleEntity;
import com.tys.legalbases.domain.model.entity.NationalNormEntity;
import com.tys.legalbases.infrastructure.external.dtos.DatosGovCoNormDTO;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

import java.util.List;

@Mapper(componentModel = "spring")
public interface NationalNormMapper {

    NationalNormMapper INSTANCE = Mappers.getMapper(NationalNormMapper.class);

    LegalBaseDTO toDto(NationalNormEntity entity);
    LegalBaseRagDTO toRagDto(NationalNormEntity entity);
    NationalNormArticleDTO toArticleDto(ArticleEntity entity);
    NationalNormEntity toEntity(LegalBaseDTO dto);
    @Mapping(target = "articles", ignore = true)
    NationalNormEntity toEntity(LegalBaseSaveDto dto);
    @Mapping(target = "nationalNorm", ignore = true)
    ArticleEntity toArticleEntity(NationalNormArticleDTO dto);
    List<LegalBaseDTO> toDtoList(List<NationalNormEntity> entities);
    List<LegalBaseRagDTO> toRagDtoList(List<NationalNormEntity> entities);
    List<NationalNormEntity> toEntityList(List<LegalBaseDTO> dtos); // New method to map list of DTOs to list of Entities
    List<NationalNormEntity> toEntityFomrGovDto(List<DatosGovCoNormDTO> dtos); // New method to map list of DTOs to list of Entities

    @Mapping(target = "id", ignore = true) // ID is generated by our DB, not from external source
    @Mapping(target = "title", source = "titulo")
    @Mapping(target = "description", source = "descripcion")
    @Mapping(target = "type", source = "tipo")
    @Mapping(target = "publishedAt", source = "fechaPublicacion")
    @Mapping(target = "sourceUrl", source = "urlFuente")
    LegalBaseDTO toDto(DatosGovCoNormDTO externalDTO);

    List<NationalNormEntity> toDtoListFromExternal(List<DatosGovCoNormDTO> externalDTOs);
}
